project_id = "qashsyjrazmkhgeesglb"

[functions.generate-roadmap]
verify_jwt = true

[functions.refine-role]
verify_jwt = true

[functions.generate-review-questions]
verify_jwt = true

[functions.validate-access-key]
verify_jwt = false

[functions.generate-skills]
verify_jwt = true

[functions.employee-auth]
verify_jwt = false

[functions.submit-self-assessment]
verify_jwt = false

[functions.send-evaluation-invite]
verify_jwt = true

[functions.update-roadmap-progress]
verify_jwt = true
