// Static demo data for users without access key
import { JobRole, Skill, Employee, CareerRoadmap } from '@/types';
import { CostCenterWithCount } from '@/hooks/useCostCenters';
import type { Treinamento } from '@/hooks/useTreinamentos';
import type { Candidato, Vaga, Candidatura } from '@/types/recruitment';
import type { Test, TestAttempt, Certification, KnowledgeBaseItem } from '@/types/tests';

export const demoEmployees: Employee[] = [
  {
    id: 'demo-1',
    name: 'Maria Silva',
    email: 'maria.silva@demo.com',
    roleId: 'cargo-1',
    admissionDate: '2022-03-15',
  },
  {
    id: 'demo-2',
    name: 'João Santos',
    email: 'joao.santos@demo.com',
    roleId: 'cargo-2',
    admissionDate: '2023-01-10',
  },
  {
    id: 'demo-3',
    name: 'Ana Oliveira',
    email: 'ana.oliveira@demo.com',
    roleId: 'cargo-3',
    admissionDate: '2021-06-20',
  },
  {
    id: 'demo-4',
    name: 'Carlos Ferreira',
    email: 'carlos.ferreira@demo.com',
    roleId: 'cargo-4',
    admissionDate: '2020-11-05',
  },
  {
    id: 'demo-5',
    name: 'Lucia Mendes',
    email: 'lucia.mendes@demo.com',
    roleId: 'cargo-5',
    admissionDate: '2019-08-12',
  },
];

export const demoCargos: JobRole[] = [
  {
    id: 'cargo-1',
    title: 'Desenvolvedor Sênior',
    level: 'Sênior',
    salaryRange: { min: 12000, max: 18000 },
    description: 'Responsável pelo desenvolvimento de aplicações complexas',
    department: 'Tecnologia',
    requiredSkillIds: ['skill-1', 'skill-2'],
    hardSkills: 'React, TypeScript, Node.js, PostgreSQL',
    softSkills: 'Liderança técnica, Mentoria, Comunicação',
  },
  {
    id: 'cargo-2',
    title: 'Desenvolvedor Pleno',
    level: 'Pleno',
    salaryRange: { min: 7000, max: 12000 },
    description: 'Desenvolvimento de features e manutenção de sistemas',
    department: 'Tecnologia',
    requiredSkillIds: ['skill-1'],
    hardSkills: 'React, JavaScript, APIs REST',
    softSkills: 'Trabalho em equipe, Proatividade',
  },
  {
    id: 'cargo-3',
    title: 'Product Manager Sênior',
    level: 'Sênior',
    salaryRange: { min: 15000, max: 22000 },
    description: 'Gestão de produtos digitais e roadmap estratégico',
    department: 'Produto',
    requiredSkillIds: ['skill-5'],
    hardSkills: 'Gestão de produto, Métricas, Roadmap',
    softSkills: 'Visão estratégica, Negociação, Liderança',
  },
  {
    id: 'cargo-4',
    title: 'Analista de RH Pleno',
    level: 'Pleno',
    salaryRange: { min: 5000, max: 8000 },
    description: 'Gestão de processos de RH e desenvolvimento humano',
    department: 'Recursos Humanos',
    requiredSkillIds: ['skill-4'],
    hardSkills: 'Recrutamento, Treinamento, Legislação trabalhista',
    softSkills: 'Empatia, Organização, Comunicação',
  },
  {
    id: 'cargo-5',
    title: 'Analista Financeiro Sênior',
    level: 'Sênior',
    salaryRange: { min: 10000, max: 15000 },
    description: 'Análise financeira e planejamento orçamentário',
    department: 'Financeiro',
    requiredSkillIds: ['skill-6'],
    hardSkills: 'Contabilidade, Excel avançado, FP&A',
    softSkills: 'Análise crítica, Atenção a detalhes',
  },
];

export const demoSkills: Skill[] = [
  // Technical
  { id: 'skill-1', name: 'React', category: 'Technical', description: 'Biblioteca JavaScript para interfaces' },
  { id: 'skill-2', name: 'TypeScript', category: 'Technical', description: 'Superset tipado de JavaScript' },
  { id: 'skill-5', name: 'Gestão de Projetos', category: 'Technical', description: 'Planejamento e execução de projetos' },
  { id: 'skill-6', name: 'SQL', category: 'Technical', description: 'Linguagem de consulta a bancos de dados' },
  { id: 'skill-9', name: 'Python', category: 'Technical', description: 'Linguagem de programação versátil' },
  { id: 'skill-10', name: 'Node.js', category: 'Technical', description: 'Runtime JavaScript server-side' },
  { id: 'skill-11', name: 'Git', category: 'Technical', description: 'Controle de versão de código' },
  { id: 'skill-12', name: 'Docker', category: 'Technical', description: 'Containerização de aplicações' },
  // Soft Skills
  { id: 'skill-4', name: 'Comunicação', category: 'Soft Skill', description: 'Expressar ideias com clareza' },
  { id: 'skill-7', name: 'Trabalho em Equipe', category: 'Soft Skill', description: 'Colaboração efetiva com colegas' },
  { id: 'skill-8', name: 'Resolução de Problemas', category: 'Soft Skill', description: 'Análise e solução de desafios complexos' },
  { id: 'skill-13', name: 'Pensamento Crítico', category: 'Soft Skill', description: 'Avaliar informações de forma objetiva' },
  { id: 'skill-14', name: 'Adaptabilidade', category: 'Soft Skill', description: 'Flexibilidade para mudanças' },
  // Leadership
  { id: 'skill-3', name: 'Liderança', category: 'Leadership', description: 'Capacidade de guiar e inspirar equipes' },
  { id: 'skill-15', name: 'Gestão de Pessoas', category: 'Leadership', description: 'Desenvolver e motivar colaboradores' },
  { id: 'skill-16', name: 'Tomada de Decisão', category: 'Leadership', description: 'Escolher a melhor ação estratégica' },
  { id: 'skill-17', name: 'Delegação', category: 'Leadership', description: 'Distribuir tarefas eficientemente' },
  // Languages
  { id: 'skill-18', name: 'Inglês Avançado', category: 'Language', description: 'Fluência em comunicação profissional' },
  { id: 'skill-19', name: 'Espanhol Intermediário', category: 'Language', description: 'Comunicação básica em espanhol' },
  { id: 'skill-20', name: 'Inglês Técnico', category: 'Language', description: 'Leitura de documentação técnica' },
];

export const demoRoadmaps: CareerRoadmap[] = [
  {
    id: 'roadmap-demo-1',
    employeeId: 'demo-2',
    employeeName: 'João Santos',
    sourceRoleTitle: 'Desenvolvedor Pleno',
    targetRoleTitle: 'Desenvolvedor Sênior',
    createdAt: '2024-10-15T10:00:00Z',
    steps: [
      {
        title: 'Dominar arquitetura de software',
        description: 'Aprofundar conhecimentos em padrões de arquitetura como Clean Architecture, DDD e microsserviços.',
        estimatedDuration: '3 meses',
        requiredSkills: ['Clean Architecture', 'Design Patterns', 'Microsserviços'],
      },
      {
        title: 'Liderança técnica',
        description: 'Desenvolver habilidades de mentoria, code review e tomada de decisão técnica.',
        estimatedDuration: '4 meses',
        requiredSkills: ['Mentoria', 'Code Review', 'Comunicação'],
      },
      {
        title: 'Especialização em performance',
        description: 'Otimização de aplicações, monitoramento e resolução de gargalos.',
        estimatedDuration: '2 meses',
        requiredSkills: ['Performance', 'Profiling', 'Caching'],
      },
      {
        title: 'DevOps e infraestrutura',
        description: 'Compreender CI/CD, containers e cloud para autonomia completa.',
        estimatedDuration: '3 meses',
        requiredSkills: ['Docker', 'Kubernetes', 'AWS/GCP'],
      },
    ],
    progress: {
      currentStepIndex: 1,
      progressPercentage: 35,
      completedSteps: [0],
      achievements: [
        { title: 'Arquitetura Dominada', description: 'Completou o estudo de Clean Architecture', type: 'milestone' },
        { title: 'Primeiro Mentoria', description: 'Realizou primeira sessão de mentoria com estagiário', type: 'skill' },
      ],
      gaps: [
        { skill: 'Kubernetes', priority: 'medium', recommendation: 'Fazer curso certificado de Kubernetes' },
        { skill: 'Comunicação executiva', priority: 'low', recommendation: 'Praticar apresentações para stakeholders' },
      ],
      nextActions: [
        'Liderar próximo code review da squad',
        'Apresentar proposta de arquitetura para novo módulo',
        'Iniciar estudo de Docker avançado',
      ],
      summary: 'João está progredindo bem na trilha para Sênior, com destaque em arquitetura. Próximo foco: liderança técnica.',
      lastUpdated: '2024-11-20T14:30:00Z',
      updateHistory: [
        {
          date: '2024-11-20T14:30:00Z',
          acquiredSkills: ['Clean Architecture', 'Design Patterns'],
          completedTrainings: [
            { name: 'Clean Architecture na Prática', date: '2024-11-10', institution: 'Udemy' },
          ],
        },
      ],
      history: [
        { date: '2024-10-20', percentage: 10, achievementsCount: 0 },
        { date: '2024-11-05', percentage: 20, achievementsCount: 1 },
        { date: '2024-11-20', percentage: 35, achievementsCount: 2 },
      ],
    },
  },
  {
    id: 'roadmap-demo-2',
    employeeId: 'demo-4',
    employeeName: 'Carlos Ferreira',
    sourceRoleTitle: 'Analista de RH Pleno',
    targetRoleTitle: 'Coordenador de RH',
    createdAt: '2024-09-01T09:00:00Z',
    steps: [
      {
        title: 'Gestão de equipes',
        description: 'Desenvolver competências de liderança e gestão de pessoas.',
        estimatedDuration: '4 meses',
        requiredSkills: ['Liderança', 'Feedback', 'Gestão de conflitos'],
      },
      {
        title: 'Indicadores e métricas de RH',
        description: 'Dominar KPIs de RH, turnover, clima organizacional e people analytics.',
        estimatedDuration: '3 meses',
        requiredSkills: ['People Analytics', 'Excel avançado', 'Power BI'],
      },
      {
        title: 'Legislação trabalhista avançada',
        description: 'Aprofundar conhecimento em legislação e compliance trabalhista.',
        estimatedDuration: '2 meses',
        requiredSkills: ['CLT', 'Compliance', 'Auditoria'],
      },
      {
        title: 'Planejamento estratégico de RH',
        description: 'Desenvolver visão estratégica e alinhamento com objetivos organizacionais.',
        estimatedDuration: '3 meses',
        requiredSkills: ['Planejamento estratégico', 'OKRs', 'Business Partner'],
      },
    ],
    progress: {
      currentStepIndex: 2,
      progressPercentage: 60,
      completedSteps: [0, 1],
      achievements: [
        { title: 'Líder de Projeto', description: 'Liderou projeto de clima organizacional', type: 'milestone' },
        { title: 'Dashboard de RH', description: 'Criou primeiro dashboard de indicadores', type: 'skill' },
        { title: 'Certificação People Analytics', description: 'Obteve certificação em People Analytics', type: 'training' },
      ],
      gaps: [
        { skill: 'Legislação internacional', priority: 'low', recommendation: 'Estudar legislação para expansão internacional' },
      ],
      nextActions: [
        'Participar de workshop de legislação trabalhista',
        'Apresentar análise de turnover para diretoria',
        'Acompanhar processo de auditoria trabalhista',
      ],
      summary: 'Carlos demonstra excelente evolução, especialmente em analytics. Foco atual: aprofundar legislação.',
      lastUpdated: '2024-12-01T11:00:00Z',
      updateHistory: [
        {
          date: '2024-10-15T10:00:00Z',
          acquiredSkills: ['Liderança', 'Gestão de conflitos'],
          completedTrainings: [
            { name: 'Liderança para RH', date: '2024-10-10', institution: 'FGV' },
          ],
        },
        {
          date: '2024-12-01T11:00:00Z',
          acquiredSkills: ['People Analytics', 'Power BI'],
          completedTrainings: [
            { name: 'People Analytics Fundamentals', date: '2024-11-25', institution: 'Coursera' },
          ],
        },
      ],
      history: [
        { date: '2024-09-15', percentage: 10, achievementsCount: 0 },
        { date: '2024-10-15', percentage: 30, achievementsCount: 1 },
        { date: '2024-11-15', percentage: 45, achievementsCount: 2 },
        { date: '2024-12-01', percentage: 60, achievementsCount: 3 },
      ],
    },
  },
  {
    id: 'roadmap-demo-3',
    employeeName: 'Ana Oliveira',
    sourceRoleTitle: 'Product Manager Sênior',
    targetRoleTitle: 'Head de Produto',
    createdAt: '2024-11-01T08:00:00Z',
    steps: [
      {
        title: 'Visão de portfólio de produtos',
        description: 'Desenvolver capacidade de gerenciar múltiplos produtos simultaneamente.',
        estimatedDuration: '4 meses',
        requiredSkills: ['Gestão de portfólio', 'Priorização estratégica', 'Roadmap'],
      },
      {
        title: 'Liderança de times de produto',
        description: 'Gerenciar e desenvolver outros PMs e times de produto.',
        estimatedDuration: '5 meses',
        requiredSkills: ['Gestão de PMs', 'Coaching', 'Desenvolvimento de carreira'],
      },
      {
        title: 'Estratégia de negócio',
        description: 'Alinhar produto com estratégia de negócio e resultados financeiros.',
        estimatedDuration: '3 meses',
        requiredSkills: ['Business Strategy', 'P&L', 'Unit Economics'],
      },
    ],
    progress: {
      currentStepIndex: 0,
      progressPercentage: 15,
      completedSteps: [],
      achievements: [
        { title: 'Mentora de PM Jr', description: 'Iniciou programa de mentoria', type: 'skill' },
      ],
      gaps: [
        { skill: 'Gestão financeira', priority: 'high', recommendation: 'Curso de finanças para não-financeiros' },
        { skill: 'Apresentação executiva', priority: 'medium', recommendation: 'Treinar apresentações para C-level' },
      ],
      nextActions: [
        'Participar de reunião de planejamento estratégico',
        'Fazer curso de Unit Economics',
        'Shadowing com atual Head de Produto',
      ],
      summary: 'Ana está no início da jornada para Head. Próximo foco: desenvolver visão de portfólio.',
      lastUpdated: '2024-11-15T16:00:00Z',
      updateHistory: [],
      history: [
        { date: '2024-11-05', percentage: 5, achievementsCount: 0 },
        { date: '2024-11-15', percentage: 15, achievementsCount: 1 },
      ],
    },
  },
];


export const demoPerformanceReviews = [
  {
    id: 'review-demo-1',
    employeeId: 'demo-1',
    employeeName: 'Maria Silva',
    date: '2024-11-15',
    status: 'Completed' as const,
    questions: [
      { id: 'q1', question: 'Como você avalia o cumprimento de metas e objetivos?', type: 'rating' as const },
      { id: 'q2', question: 'Como você avalia a qualidade do trabalho entregue?', type: 'rating' as const },
      { id: 'q3', question: 'Como você avalia a colaboração e trabalho em equipe?', type: 'rating' as const },
      { id: 'q4', question: 'Como você avalia a comunicação e proatividade?', type: 'rating' as const },
      { id: 'q5', question: 'Quais foram os principais pontos fortes demonstrados?', type: 'text' as const },
      { id: 'q6', question: 'Quais áreas precisam de desenvolvimento?', type: 'text' as const },
    ],
    responses: [
      { questionId: 'q1', rating: 5 },
      { questionId: 'q2', rating: 5 },
      { questionId: 'q3', rating: 4 },
      { questionId: 'q4', rating: 4 },
      { questionId: 'q5', text: 'Excelente capacidade técnica, liderança natural, resolução de problemas complexos.' },
      { questionId: 'q6', text: 'Pode melhorar na delegação de tarefas e documentação.' },
    ],
    overallFeedback: 'Maria continua sendo uma referência técnica para a equipe. Recomendado para promoção.',
    createdAt: '2024-11-15T10:00:00Z',
  },
  {
    id: 'review-demo-2',
    employeeId: 'demo-2',
    employeeName: 'João Santos',
    date: '2024-11-20',
    status: 'Completed' as const,
    questions: [
      { id: 'q1', question: 'Como você avalia o cumprimento de metas e objetivos?', type: 'rating' as const },
      { id: 'q2', question: 'Como você avalia a qualidade do trabalho entregue?', type: 'rating' as const },
      { id: 'q3', question: 'Como você avalia a colaboração e trabalho em equipe?', type: 'rating' as const },
      { id: 'q4', question: 'Como você avalia a comunicação e proatividade?', type: 'rating' as const },
      { id: 'q5', question: 'Quais foram os principais pontos fortes demonstrados?', type: 'text' as const },
      { id: 'q6', question: 'Quais áreas precisam de desenvolvimento?', type: 'text' as const },
    ],
    responses: [
      { questionId: 'q1', rating: 4 },
      { questionId: 'q2', rating: 4 },
      { questionId: 'q3', rating: 5 },
      { questionId: 'q4', rating: 4 },
      { questionId: 'q5', text: 'Ótimo trabalho em equipe, rápida evolução técnica, comprometimento.' },
      { questionId: 'q6', text: 'Aprofundar conhecimentos em arquitetura de software.' },
    ],
    overallFeedback: 'João está evoluindo bem e demonstra potencial para assumir mais responsabilidades.',
    createdAt: '2024-11-20T14:00:00Z',
  },
  {
    id: 'review-demo-3',
    employeeId: 'demo-4',
    employeeName: 'Carlos Ferreira',
    date: '2024-12-01',
    status: 'PendingManager' as const,
    questions: [
      { id: 'q1', question: 'Como você avalia o cumprimento de metas e objetivos?', type: 'rating' as const },
      { id: 'q2', question: 'Como você avalia a qualidade do trabalho entregue?', type: 'rating' as const },
      { id: 'q3', question: 'Como você avalia a colaboração e trabalho em equipe?', type: 'rating' as const },
      { id: 'q4', question: 'Como você avalia a comunicação e proatividade?', type: 'rating' as const },
      { id: 'q5', question: 'Quais foram os principais pontos fortes demonstrados?', type: 'text' as const },
      { id: 'q6', question: 'Quais áreas precisam de desenvolvimento?', type: 'text' as const },
    ],
    responses: [
      { questionId: 'q1', rating: 4 },
      { questionId: 'q2', rating: 5 },
      { questionId: 'q3', rating: 4 },
      { questionId: 'q4', rating: 4 },
      { questionId: 'q5', text: 'Organização, conhecimento de processos, relacionamento interpessoal.' },
      { questionId: 'q6', text: 'Desenvolver visão estratégica e conhecimento de people analytics.' },
    ],
    overallFeedback: null,
    createdAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'review-demo-4',
    employeeId: 'demo-3',
    employeeName: 'Ana Oliveira',
    date: '2024-12-05',
    status: 'PendingSelf' as const,
    questions: [
      { id: 'q1', question: 'Como você avalia o cumprimento de metas e objetivos?', type: 'rating' as const },
      { id: 'q2', question: 'Como você avalia a qualidade do trabalho entregue?', type: 'rating' as const },
      { id: 'q3', question: 'Como você avalia a colaboração e trabalho em equipe?', type: 'rating' as const },
      { id: 'q4', question: 'Como você avalia a comunicação e proatividade?', type: 'rating' as const },
      { id: 'q5', question: 'Quais foram os principais pontos fortes demonstrados?', type: 'text' as const },
      { id: 'q6', question: 'Quais áreas precisam de desenvolvimento?', type: 'text' as const },
    ],
    responses: [],
    overallFeedback: null,
    createdAt: '2024-12-05T08:00:00Z',
  },
];

export const demoEvaluationCycles = [
  {
    id: 'cycle-demo-1',
    title: 'Avaliação Anual 2024',
    description: 'Ciclo de avaliação de desempenho do ano de 2024',
    start_date: '2024-11-01',
    end_date: '2024-12-15',
    status: 'active' as const,
    created_at: '2024-11-01T00:00:00Z',
  },
  {
    id: 'cycle-demo-2',
    title: 'Avaliação Semestral 2024/1',
    description: 'Primeira avaliação semestral de 2024',
    start_date: '2024-06-01',
    end_date: '2024-06-30',
    status: 'closed' as const,
    created_at: '2024-06-01T00:00:00Z',
  },
];

export const demoEvaluations = [
  {
    id: 'eval-demo-1',
    cycle_id: 'cycle-demo-1',
    employee_id: 'demo-1',
    status: 'completed' as const,
    questions: [
      { id: 'eq1', question: 'Quais foram suas maiores realizações neste período?', category: 'Resultados', type: 'text' },
      { id: 'eq2', question: 'Quais desafios você enfrentou?', category: 'Desafios', type: 'text' },
      { id: 'eq3', question: 'Como você avalia sua colaboração com a equipe?', category: 'Trabalho em Equipe', type: 'rating' },
    ],
    self_assessment_responses: [
      { questionId: 'eq1', response: 'Liderei a migração do sistema legado e reduzi bugs em 40%.' },
      { questionId: 'eq2', response: 'Integração com sistemas externos e gestão de prazos apertados.' },
      { questionId: 'eq3', rating: 5 },
    ],
    manager_evaluation_responses: [
      { questionId: 'eq1', response: 'Excelente liderança técnica na migração.' },
      { questionId: 'eq2', response: 'Superou desafios com maturidade.' },
      { questionId: 'eq3', rating: 5 },
    ],
    manager_feedback: 'Maria é uma profissional excepcional, pronta para novos desafios.',
    self_assessment_completed_at: '2024-11-10T14:00:00Z',
    manager_evaluation_completed_at: '2024-11-15T16:00:00Z',
    employee: {
      id: 'demo-1',
      nome: 'Maria Silva',
      name: 'Maria Silva',
      email: 'maria.silva@demo.com',
    },
  },
  {
    id: 'eval-demo-2',
    cycle_id: 'cycle-demo-1',
    employee_id: 'demo-2',
    status: 'self_assessment_done' as const,
    questions: [
      { id: 'eq1', question: 'Quais foram suas maiores realizações neste período?', category: 'Resultados', type: 'text' },
      { id: 'eq2', question: 'Quais desafios você enfrentou?', category: 'Desafios', type: 'text' },
      { id: 'eq3', question: 'Como você avalia sua colaboração com a equipe?', category: 'Trabalho em Equipe', type: 'rating' },
    ],
    self_assessment_responses: [
      { questionId: 'eq1', response: 'Implementei 3 features principais e melhorei cobertura de testes.' },
      { questionId: 'eq2', response: 'Adaptação a novas tecnologias e gestão de múltiplas demandas.' },
      { questionId: 'eq3', rating: 4 },
    ],
    manager_evaluation_responses: null,
    manager_feedback: null,
    self_assessment_completed_at: '2024-11-18T11:00:00Z',
    manager_evaluation_completed_at: null,
    employee: {
      id: 'demo-2',
      nome: 'João Santos',
      name: 'João Santos',
      email: 'joao.santos@demo.com',
    },
  },
  {
    id: 'eval-demo-3',
    cycle_id: 'cycle-demo-1',
    employee_id: 'demo-4',
    status: 'pending' as const,
    questions: [
      { id: 'eq1', question: 'Quais foram suas maiores realizações neste período?', category: 'Resultados', type: 'text' },
      { id: 'eq2', question: 'Quais desafios você enfrentou?', category: 'Desafios', type: 'text' },
      { id: 'eq3', question: 'Como você avalia sua colaboração com a equipe?', category: 'Trabalho em Equipe', type: 'rating' },
    ],
    self_assessment_responses: null,
    manager_evaluation_responses: null,
    manager_feedback: null,
    self_assessment_completed_at: null,
    manager_evaluation_completed_at: null,
    employee: {
      id: 'demo-4',
      nome: 'Carlos Ferreira',
      name: 'Carlos Ferreira',
      email: 'carlos.ferreira@demo.com',
    },
  },
];

export const demoStats = {
  totalEmployees: 5,
  totalRoles: 5,
  totalSkills: 8,
  totalCostCenters: 4,
  avgSalary: 11400,
  pendingReviews: 2,
};

export const demoEmpresas = [
  {
    id: 'empresa-1',
    codempresa: 'EMP001',
    nomeempresa: 'Tech Solutions Ltda',
    cnae: '6201-5/00',
    grau_risco: 1,
    percentual_encargos: 80,
  },
  {
    id: 'empresa-2',
    codempresa: 'EMP002',
    nomeempresa: 'Consultoria ABC',
    cnae: '7020-4/00',
    grau_risco: 1,
    percentual_encargos: 75,
  },
];

export const demoCostCenters: CostCenterWithCount[] = [
  {
    id: 'cc-1',
    codcentrodecustos: 'CC001',
    nomecentrodecustos: 'Desenvolvimento de Software',
    codempresa: 'EMP001',
    employeeCount: 3,
  },
  {
    id: 'cc-2',
    codcentrodecustos: 'CC002',
    nomecentrodecustos: 'Recursos Humanos',
    codempresa: 'EMP001',
    employeeCount: 1,
  },
  {
    id: 'cc-3',
    codcentrodecustos: 'CC003',
    nomecentrodecustos: 'Comercial e Vendas',
    codempresa: 'EMP002',
    employeeCount: 1,
  },
  {
    id: 'cc-4',
    codcentrodecustos: 'CC004',
    nomecentrodecustos: 'Administrativo',
    codempresa: 'EMP002',
    employeeCount: 0,
  },
];

// ==========================================
// TREINAMENTOS (Trainings) Demo Data
// ==========================================
export const demoTreinamentos: Treinamento[] = [
  {
    id: 'treinamento-demo-1',
    employee_id: 'demo-1',
    nome_treinamento: 'React Avançado e Design Patterns',
    instituicao: 'Alura',
    data_inicio: '2024-09-01',
    data_conclusao: '2024-10-15',
    carga_horaria: 40,
    certificado_url: null,
    status: 'concluido',
    observacoes: 'Treinamento focado em hooks avançados, Context API e padrões de projeto.',
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
  },
  {
    id: 'treinamento-demo-2',
    employee_id: 'demo-2',
    nome_treinamento: 'Clean Architecture na Prática',
    instituicao: 'Udemy',
    data_inicio: '2024-10-01',
    data_conclusao: '2024-11-10',
    carga_horaria: 32,
    certificado_url: null,
    status: 'concluido',
    observacoes: 'Estudos de Clean Architecture, SOLID e DDD aplicados a projetos reais.',
    created_at: '2024-10-01T10:00:00Z',
    updated_at: '2024-11-10T10:00:00Z',
  },
  {
    id: 'treinamento-demo-3',
    employee_id: 'demo-3',
    nome_treinamento: 'Product Discovery e Estratégia',
    instituicao: 'PM3',
    data_inicio: '2024-11-01',
    data_conclusao: null,
    carga_horaria: 60,
    certificado_url: null,
    status: 'em_andamento',
    observacoes: 'Formação completa em discovery, user research e product strategy.',
    created_at: '2024-11-01T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
  },
  {
    id: 'treinamento-demo-4',
    employee_id: 'demo-4',
    nome_treinamento: 'People Analytics Fundamentals',
    instituicao: 'Coursera',
    data_inicio: '2024-10-15',
    data_conclusao: '2024-11-25',
    carga_horaria: 24,
    certificado_url: null,
    status: 'concluido',
    observacoes: 'Fundamentos de analytics aplicados a RH, dashboards e métricas.',
    created_at: '2024-10-15T10:00:00Z',
    updated_at: '2024-11-25T10:00:00Z',
  },
  {
    id: 'treinamento-demo-5',
    employee_id: 'demo-5',
    nome_treinamento: 'FP&A - Planejamento Financeiro',
    instituicao: 'FGV Online',
    data_inicio: '2024-08-01',
    data_conclusao: '2024-09-30',
    carga_horaria: 48,
    certificado_url: null,
    status: 'concluido',
    observacoes: 'Planejamento financeiro, análise orçamentária e modelagem.',
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2024-09-30T10:00:00Z',
  },
  {
    id: 'treinamento-demo-6',
    employee_id: 'demo-1',
    nome_treinamento: 'Liderança para Tech Leads',
    instituicao: 'LinkedIn Learning',
    data_inicio: '2024-12-01',
    data_conclusao: null,
    carga_horaria: 20,
    certificado_url: null,
    status: 'em_andamento',
    observacoes: 'Desenvolvimento de soft skills para liderança técnica.',
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'treinamento-demo-7',
    employee_id: 'demo-4',
    nome_treinamento: 'Legislação Trabalhista Atualizada',
    instituicao: 'IBMEC',
    data_inicio: '2024-07-01',
    data_conclusao: '2024-07-20',
    carga_horaria: 16,
    certificado_url: null,
    status: 'concluido',
    observacoes: 'Atualização em CLT, eSocial e compliance trabalhista.',
    created_at: '2024-07-01T10:00:00Z',
    updated_at: '2024-07-20T10:00:00Z',
  },
];

// ==========================================
// RECRUITMENT Demo Data
// ==========================================
export const demoCandidatos: Candidato[] = [
  {
    id: 'cand-demo-1',
    nome: 'Rafael Costa',
    email: 'rafael.costa@email.com',
    telefone: '(11) 98765-4321',
    cidade: 'São Paulo',
    estado: 'SP',
    linkedin_url: 'https://linkedin.com/in/rafaelcosta',
    resumo_profissional: 'Desenvolvedor Full Stack com 5 anos de experiência em React, Node.js e AWS. Especialista em microsserviços e arquitetura cloud.',
    pretensao_salarial: 14000,
    disponibilidade: 'imediata',
    fonte: 'LinkedIn',
    status: 'ativo',
    created_at: '2024-11-01T10:00:00Z',
    skills: [
      { id: 'cs-1', candidato_id: 'cand-demo-1', skill_name: 'React', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 4 },
      { id: 'cs-2', candidato_id: 'cand-demo-1', skill_name: 'Node.js', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 5 },
      { id: 'cs-3', candidato_id: 'cand-demo-1', skill_name: 'TypeScript', skill_category: 'Technical', nivel: 'intermediario', anos_experiencia: 3 },
    ],
    experiencias: [
      { id: 'exp-1', candidato_id: 'cand-demo-1', empresa: 'TechCorp', cargo: 'Desenvolvedor Pleno', data_inicio: '2021-03', data_fim: '2024-10', atual: false, descricao: 'Desenvolvimento de APIs e front-end com React.' },
    ],
    formacoes: [
      { id: 'form-1', candidato_id: 'cand-demo-1', instituicao: 'USP', curso: 'Ciência da Computação', nivel: 'graduacao', data_conclusao: '2020-12', em_andamento: false },
    ],
  },
  {
    id: 'cand-demo-2',
    nome: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    telefone: '(21) 99876-5432',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    resumo_profissional: 'Product Manager com 7 anos de experiência em empresas de tecnologia. Forte em discovery, métricas e gestão de stakeholders.',
    pretensao_salarial: 18000,
    disponibilidade: '30 dias',
    fonte: 'Indicação',
    status: 'ativo',
    created_at: '2024-11-05T10:00:00Z',
    skills: [
      { id: 'cs-4', candidato_id: 'cand-demo-2', skill_name: 'Gestão de Produto', skill_category: 'Technical', nivel: 'especialista', anos_experiencia: 7 },
      { id: 'cs-5', candidato_id: 'cand-demo-2', skill_name: 'Análise de Dados', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 5 },
    ],
    experiencias: [
      { id: 'exp-2', candidato_id: 'cand-demo-2', empresa: 'StartupXYZ', cargo: 'Product Manager Senior', data_inicio: '2020-01', atual: true, descricao: 'Liderança de squad de produto, discovery e delivery.' },
    ],
    formacoes: [
      { id: 'form-2', candidato_id: 'cand-demo-2', instituicao: 'PUC-RJ', curso: 'Administração de Empresas', nivel: 'graduacao', data_conclusao: '2017-12', em_andamento: false },
      { id: 'form-3', candidato_id: 'cand-demo-2', instituicao: 'FGV', curso: 'MBA em Gestão de Produto', nivel: 'pos_graduacao', data_conclusao: '2020-06', em_andamento: false },
    ],
  },
  {
    id: 'cand-demo-3',
    nome: 'Bruno Almeida',
    email: 'bruno.almeida@email.com',
    telefone: '(31) 97654-3210',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    resumo_profissional: 'Analista de RH com experiência em recrutamento, treinamento e desenvolvimento organizacional. Certificado em DISC e MBTI.',
    pretensao_salarial: 6500,
    disponibilidade: 'imediata',
    fonte: 'Site Carreiras',
    status: 'ativo',
    created_at: '2024-11-10T10:00:00Z',
    skills: [
      { id: 'cs-6', candidato_id: 'cand-demo-3', skill_name: 'Recrutamento e Seleção', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 4 },
      { id: 'cs-7', candidato_id: 'cand-demo-3', skill_name: 'Treinamento e Desenvolvimento', skill_category: 'Technical', nivel: 'intermediario', anos_experiencia: 3 },
    ],
    experiencias: [],
    formacoes: [
      { id: 'form-4', candidato_id: 'cand-demo-3', instituicao: 'UFMG', curso: 'Psicologia', nivel: 'graduacao', data_conclusao: '2019-12', em_andamento: false },
    ],
  },
  {
    id: 'cand-demo-4',
    nome: 'Isabela Rodrigues',
    email: 'isabela.rodrigues@email.com',
    telefone: '(41) 96543-2109',
    cidade: 'Curitiba',
    estado: 'PR',
    resumo_profissional: 'Desenvolvedora Front-end com experiência em React, Vue.js e design systems. Apaixonada por acessibilidade e UX.',
    pretensao_salarial: 10000,
    disponibilidade: '15 dias',
    fonte: 'GitHub',
    status: 'ativo',
    created_at: '2024-11-15T10:00:00Z',
    skills: [
      { id: 'cs-8', candidato_id: 'cand-demo-4', skill_name: 'React', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 4 },
      { id: 'cs-9', candidato_id: 'cand-demo-4', skill_name: 'CSS/Tailwind', skill_category: 'Technical', nivel: 'especialista', anos_experiencia: 5 },
      { id: 'cs-10', candidato_id: 'cand-demo-4', skill_name: 'Acessibilidade Web', skill_category: 'Technical', nivel: 'avancado', anos_experiencia: 3 },
    ],
    experiencias: [
      { id: 'exp-3', candidato_id: 'cand-demo-4', empresa: 'DesignStudio', cargo: 'Front-end Developer', data_inicio: '2022-06', atual: true, descricao: 'Desenvolvimento de design system e interfaces acessíveis.' },
    ],
    formacoes: [
      { id: 'form-5', candidato_id: 'cand-demo-4', instituicao: 'UTFPR', curso: 'Engenharia de Software', nivel: 'graduacao', data_conclusao: '2021-12', em_andamento: false },
    ],
  },
];

export const demoVagas: Vaga[] = [
  {
    id: 'vaga-demo-1',
    titulo: 'Desenvolvedor Full Stack Sênior',
    cargo_titulo: 'Desenvolvedor Sênior',
    descricao: 'Buscamos um desenvolvedor sênior para liderar projetos de alta complexidade, definir arquitetura e mentorar a equipe.',
    requisitos: 'Experiência com React, Node.js, PostgreSQL. Conhecimento em arquitetura de microsserviços e cloud (AWS/GCP).',
    beneficios: 'Vale refeição, Plano de saúde, PLR, Home office flexível, Budget de educação',
    tipo_contrato: 'clt',
    modalidade: 'hibrido',
    local: 'São Paulo - SP',
    salario_min: 12000,
    salario_max: 18000,
    quantidade_vagas: 2,
    data_abertura: '2024-11-01',
    data_limite: '2025-01-15',
    status: 'aberta',
    prioridade: 'alta',
    publicado: true,
    created_at: '2024-11-01T10:00:00Z',
    skills: [
      { id: 'vs-1', vaga_id: 'vaga-demo-1', skill_name: 'React', skill_category: 'Technical', nivel_minimo: 'avancado', obrigatoria: true },
      { id: 'vs-2', vaga_id: 'vaga-demo-1', skill_name: 'Node.js', skill_category: 'Technical', nivel_minimo: 'avancado', obrigatoria: true },
      { id: 'vs-3', vaga_id: 'vaga-demo-1', skill_name: 'TypeScript', skill_category: 'Technical', nivel_minimo: 'intermediario', obrigatoria: false },
    ],
  },
  {
    id: 'vaga-demo-2',
    titulo: 'Product Manager',
    cargo_titulo: 'Product Manager Sênior',
    descricao: 'Vaga para PM que irá liderar a estratégia de produto digital, realizando discovery e trabalhando próximo ao time de engenharia.',
    requisitos: 'Experiência de 5+ anos em gestão de produto digital. Conhecimento em metodologias ágeis, métricas e analytics.',
    beneficios: 'Vale refeição, Plano de saúde premium, Stock options, Home office',
    tipo_contrato: 'clt',
    modalidade: 'remoto',
    salario_min: 15000,
    salario_max: 22000,
    quantidade_vagas: 1,
    data_abertura: '2024-11-10',
    data_limite: '2025-01-31',
    status: 'aberta',
    prioridade: 'normal',
    publicado: true,
    created_at: '2024-11-10T10:00:00Z',
    skills: [
      { id: 'vs-4', vaga_id: 'vaga-demo-2', skill_name: 'Gestão de Produto', skill_category: 'Technical', nivel_minimo: 'avancado', obrigatoria: true },
      { id: 'vs-5', vaga_id: 'vaga-demo-2', skill_name: 'Análise de Dados', skill_category: 'Technical', nivel_minimo: 'intermediario', obrigatoria: true },
    ],
  },
  {
    id: 'vaga-demo-3',
    titulo: 'Analista de RH Júnior',
    cargo_titulo: 'Analista de RH Pleno',
    descricao: 'Oportunidade para profissional de RH apoiar processos de recrutamento, onboarding e treinamento.',
    requisitos: 'Formação em Psicologia, Administração ou áreas afins. Experiência em R&S.',
    beneficios: 'Vale refeição, Plano de saúde, Vale transporte',
    tipo_contrato: 'clt',
    modalidade: 'presencial',
    local: 'Belo Horizonte - MG',
    salario_min: 3500,
    salario_max: 5000,
    quantidade_vagas: 1,
    data_abertura: '2024-10-15',
    status: 'em_analise',
    prioridade: 'baixa',
    publicado: false,
    created_at: '2024-10-15T10:00:00Z',
    skills: [],
  },
];

export const demoCandidaturas: Candidatura[] = [
  {
    id: 'candidatura-demo-1',
    candidato_id: 'cand-demo-1',
    vaga_id: 'vaga-demo-1',
    etapa: 'entrevista_gestor',
    status: 'em_analise',
    match_score: 87,
    match_detalhes: {
      score_skills: 90,
      score_experiencia: 85,
      score_formacao: 80,
      score_salario: 95,
      skills_match: [
        { skill: 'React', candidato_nivel: 'avancado', vaga_nivel: 'avancado', match: true },
        { skill: 'Node.js', candidato_nivel: 'avancado', vaga_nivel: 'avancado', match: true },
        { skill: 'TypeScript', candidato_nivel: 'intermediario', vaga_nivel: 'intermediario', match: true },
      ],
      gaps: [],
      pontos_fortes: ['Experiência sólida com React e Node.js', 'Formação em Ciência da Computação'],
    },
    data_candidatura: '2024-11-05T10:00:00Z',
    entrevistas: [
      {
        id: 'entrev-1',
        candidatura_id: 'candidatura-demo-1',
        tipo: 'rh',
        data_hora: '2024-11-15T14:00:00Z',
        duracao_minutos: 45,
        link_online: 'https://meet.google.com/demo',
        entrevistadores: ['Carlos Ferreira'],
        status: 'realizada',
        notas: 'Boa comunicação, motivado pela vaga.',
      },
      {
        id: 'entrev-2',
        candidatura_id: 'candidatura-demo-1',
        tipo: 'tecnica',
        data_hora: '2024-11-22T10:00:00Z',
        duracao_minutos: 60,
        link_online: 'https://meet.google.com/demo2',
        entrevistadores: ['Maria Silva'],
        status: 'realizada',
        notas: 'Excelente conhecimento técnico, resolveu o desafio com eficiência.',
      },
    ],
    feedbacks: [
      {
        id: 'fb-1',
        candidatura_id: 'candidatura-demo-1',
        tipo: 'entrevista',
        avaliador_nome: 'Maria Silva',
        nota_geral: 9,
        pontos_fortes: 'Conhecimento técnico sólido, boa arquitetura de soluções.',
        pontos_melhoria: 'Poderia explorar mais testes automatizados.',
        recomendacao: 'aprovar',
        created_at: '2024-11-22T12:00:00Z',
      },
    ],
  },
  {
    id: 'candidatura-demo-2',
    candidato_id: 'cand-demo-4',
    vaga_id: 'vaga-demo-1',
    etapa: 'teste_tecnico',
    status: 'em_analise',
    match_score: 72,
    data_candidatura: '2024-11-12T10:00:00Z',
    entrevistas: [
      {
        id: 'entrev-3',
        candidatura_id: 'candidatura-demo-2',
        tipo: 'rh',
        data_hora: '2024-11-20T15:00:00Z',
        duracao_minutos: 30,
        link_online: 'https://meet.google.com/demo3',
        entrevistadores: ['Carlos Ferreira'],
        status: 'realizada',
      },
    ],
    feedbacks: [],
  },
  {
    id: 'candidatura-demo-3',
    candidato_id: 'cand-demo-2',
    vaga_id: 'vaga-demo-2',
    etapa: 'proposta',
    status: 'aprovado',
    match_score: 94,
    match_detalhes: {
      score_skills: 95,
      score_experiencia: 95,
      score_formacao: 90,
      score_salario: 85,
      skills_match: [
        { skill: 'Gestão de Produto', candidato_nivel: 'especialista', vaga_nivel: 'avancado', match: true },
        { skill: 'Análise de Dados', candidato_nivel: 'avancado', vaga_nivel: 'intermediario', match: true },
      ],
      gaps: [],
      pontos_fortes: ['Experiência extensa em produto', 'MBA em Gestão de Produto', 'Perfil de liderança'],
    },
    data_candidatura: '2024-11-08T10:00:00Z',
    entrevistas: [
      {
        id: 'entrev-4',
        candidatura_id: 'candidatura-demo-3',
        tipo: 'rh',
        data_hora: '2024-11-14T10:00:00Z',
        duracao_minutos: 45,
        status: 'realizada',
      },
      {
        id: 'entrev-5',
        candidatura_id: 'candidatura-demo-3',
        tipo: 'gestor',
        data_hora: '2024-11-25T14:00:00Z',
        duracao_minutos: 60,
        status: 'realizada',
      },
    ],
    feedbacks: [
      {
        id: 'fb-2',
        candidatura_id: 'candidatura-demo-3',
        tipo: 'final',
        avaliador_nome: 'Ana Oliveira',
        nota_geral: 10,
        pontos_fortes: 'Perfil excepcional, alinhamento total com a vaga.',
        recomendacao: 'aprovar',
        created_at: '2024-11-26T10:00:00Z',
      },
    ],
  },
  {
    id: 'candidatura-demo-4',
    candidato_id: 'cand-demo-3',
    vaga_id: 'vaga-demo-3',
    etapa: 'triagem',
    status: 'em_analise',
    match_score: 65,
    data_candidatura: '2024-11-18T10:00:00Z',
    entrevistas: [],
    feedbacks: [],
  },
];

// ==========================================
// TESTS & CERTIFICATIONS Demo Data
// ==========================================
export const demoKnowledgeBase: KnowledgeBaseItem[] = [
  {
    id: 'kb-demo-1',
    title: 'Manual de Boas Práticas React',
    description: 'Guia completo de boas práticas para desenvolvimento com React e TypeScript.',
    content: 'Conteúdo abrangente sobre componentização, gerenciamento de estado, hooks customizados e performance.',
    cargoId: 'cargo-1',
    tags: ['React', 'TypeScript', 'Frontend'],
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'kb-demo-2',
    title: 'Processo de Onboarding - RH',
    description: 'Documentação do processo de integração de novos colaboradores.',
    content: 'Etapas do onboarding, checklist de documentos, agenda da primeira semana e mentoria.',
    cargoId: 'cargo-4',
    tags: ['RH', 'Onboarding', 'Processos'],
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'kb-demo-3',
    title: 'Políticas de Segurança da Informação',
    description: 'Políticas e diretrizes de segurança da informação da empresa.',
    content: 'LGPD, uso de senhas, VPN, classificação de dados e procedimentos de resposta a incidentes.',
    tags: ['Segurança', 'LGPD', 'Compliance'],
    createdAt: '2024-08-20T10:00:00Z',
    updatedAt: '2024-08-20T10:00:00Z',
  },
  {
    id: 'kb-demo-4',
    title: 'Metodologia Ágil e Scrum',
    description: 'Guia prático sobre metodologia ágil e framework Scrum.',
    content: 'Sprints, cerimônias, papéis, métricas e melhores práticas de times ágeis.',
    tags: ['Agile', 'Scrum', 'Gestão'],
    createdAt: '2024-07-10T10:00:00Z',
    updatedAt: '2024-07-10T10:00:00Z',
  },
];

export const demoTests: Test[] = [
  {
    id: 'test-demo-1',
    title: 'Avaliação de React e TypeScript',
    description: 'Teste técnico para desenvolvedores focado em React, hooks e TypeScript.',
    cargoId: 'cargo-1',
    participationMode: 'cargo',
    passingScore: 70,
    timeLimitMinutes: 45,
    isActive: true,
    questions: [
      {
        id: 'tq-1',
        type: 'multiple_choice',
        questionText: 'Qual hook do React é utilizado para executar efeitos colaterais?',
        options: [
          { id: 'o1', text: 'useState' },
          { id: 'o2', text: 'useEffect' },
          { id: 'o3', text: 'useRef' },
          { id: 'o4', text: 'useMemo' },
        ],
        correctAnswer: 'o2',
        points: 10,
        category: 'React',
      },
      {
        id: 'tq-2',
        type: 'multiple_choice',
        questionText: 'Qual a diferença entre interface e type no TypeScript?',
        options: [
          { id: 'o5', text: 'Não há diferença' },
          { id: 'o6', text: 'interface pode ser extendida, type não' },
          { id: 'o7', text: 'interface suporta extend e merge, type suporta unions' },
          { id: 'o8', text: 'type é mais rápido' },
        ],
        correctAnswer: 'o7',
        points: 10,
        category: 'TypeScript',
      },
      {
        id: 'tq-3',
        type: 'essay',
        questionText: 'Explique como implementar um custom hook para gerenciamento de formulários.',
        points: 20,
        category: 'React',
      },
    ],
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'test-demo-2',
    title: 'Fundamentos de Segurança da Informação',
    description: 'Teste obrigatório sobre políticas de segurança da informação e LGPD.',
    participationMode: 'self_enrollment',
    passingScore: 80,
    timeLimitMinutes: 30,
    isActive: true,
    questions: [
      {
        id: 'tq-4',
        type: 'multiple_choice',
        questionText: 'O que significa LGPD?',
        options: [
          { id: 'o9', text: 'Lei Geral de Proteção de Dados' },
          { id: 'o10', text: 'Lei Geral de Privacidade Digital' },
          { id: 'o11', text: 'Lei Global de Proteção Digital' },
          { id: 'o12', text: 'Lei Geral de Proteção e Defesa' },
        ],
        correctAnswer: 'o9',
        points: 10,
        category: 'LGPD',
      },
      {
        id: 'tq-5',
        type: 'multiple_choice',
        questionText: 'Qual prática NÃO é recomendada para segurança de senhas?',
        options: [
          { id: 'o13', text: 'Usar autenticação de dois fatores' },
          { id: 'o14', text: 'Compartilhar senhas com colegas de confiança' },
          { id: 'o15', text: 'Usar senhas longas e complexas' },
          { id: 'o16', text: 'Trocar senhas periodicamente' },
        ],
        correctAnswer: 'o14',
        points: 10,
        category: 'Segurança',
      },
    ],
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'test-demo-3',
    title: 'People Analytics e Métricas de RH',
    description: 'Avaliação sobre indicadores de RH, people analytics e uso de dados.',
    cargoId: 'cargo-4',
    participationMode: 'cargo',
    passingScore: 75,
    timeLimitMinutes: 40,
    isActive: true,
    questions: [
      {
        id: 'tq-6',
        type: 'multiple_choice',
        questionText: 'Qual métrica mede a taxa de rotatividade de colaboradores?',
        options: [
          { id: 'o17', text: 'NPS' },
          { id: 'o18', text: 'Turnover' },
          { id: 'o19', text: 'Absenteísmo' },
          { id: 'o20', text: 'Headcount' },
        ],
        correctAnswer: 'o18',
        points: 10,
        category: 'Métricas',
      },
      {
        id: 'tq-7',
        type: 'essay',
        questionText: 'Descreva como people analytics pode ajudar na retenção de talentos.',
        points: 30,
        category: 'People Analytics',
      },
    ],
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
];

export const demoTestAttempts: TestAttempt[] = [
  {
    id: 'attempt-demo-1',
    testId: 'test-demo-1',
    employeeId: 'demo-1',
    startedAt: '2024-10-20T14:00:00Z',
    completedAt: '2024-10-20T14:35:00Z',
    responses: [
      { questionId: 'tq-1', answer: 'o2', isCorrect: true, score: 10 },
      { questionId: 'tq-2', answer: 'o7', isCorrect: true, score: 10 },
      { questionId: 'tq-3', answer: 'Implementaria usando useState para gerenciar valores e erros, useCallback para handlers de mudança, e uma função validate que verifica regras customizáveis.', score: 18 },
    ],
    finalScore: 95,
    status: 'graded',
    feedback: 'Excelente desempenho! Demonstrou domínio completo de React e TypeScript.',
  },
  {
    id: 'attempt-demo-2',
    testId: 'test-demo-2',
    employeeId: 'demo-4',
    startedAt: '2024-09-15T10:00:00Z',
    completedAt: '2024-09-15T10:22:00Z',
    responses: [
      { questionId: 'tq-4', answer: 'o9', isCorrect: true, score: 10 },
      { questionId: 'tq-5', answer: 'o14', isCorrect: true, score: 10 },
    ],
    finalScore: 100,
    status: 'graded',
    feedback: 'Aprovado com nota máxima.',
  },
  {
    id: 'attempt-demo-3',
    testId: 'test-demo-1',
    employeeId: 'demo-2',
    startedAt: '2024-10-22T09:00:00Z',
    completedAt: '2024-10-22T09:40:00Z',
    responses: [
      { questionId: 'tq-1', answer: 'o2', isCorrect: true, score: 10 },
      { questionId: 'tq-2', answer: 'o6', isCorrect: false, score: 0 },
      { questionId: 'tq-3', answer: 'Usaria um hook que encapsula o estado do form com useState e retorna funções de handleChange e handleSubmit.', score: 14 },
    ],
    finalScore: 60,
    status: 'graded',
    feedback: 'Precisa aprofundar conhecimentos em TypeScript. Aprovação condicional.',
  },
];

export const demoCertifications: Certification[] = [
  {
    id: 'cert-demo-1',
    testId: 'test-demo-1',
    employeeId: 'demo-1',
    attemptId: 'attempt-demo-1',
    issuedAt: '2024-10-20T15:00:00Z',
    validUntil: '2025-10-20T15:00:00Z',
    certificateCode: 'CERT-REACT-2024-001',
  },
  {
    id: 'cert-demo-2',
    testId: 'test-demo-2',
    employeeId: 'demo-4',
    attemptId: 'attempt-demo-2',
    issuedAt: '2024-09-15T11:00:00Z',
    validUntil: '2025-09-15T11:00:00Z',
    certificateCode: 'CERT-SEC-2024-001',
  },
];
